name: coroute_framework
description: Core Flutter framework for Coroute.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1
  path_provider: ^2.0.15
  path: ^1.8.3
  http: ^1.1.0
